### ISSUE TITLE
the game cannot play with sound on snap platform

### ISSUE THREAD

**Issue by AndreaElijha** [brlin-tw/OpenSyobonAction-snap#9]
open-syobon-action             
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
Unable to init SDL_mixer: No available audio device

**Comment by brlin-tw** [comment]
Hello, apologies for the ignorance.  I can reproduce this issue at my end will investigate how to fix this problem.

**Comment by brlin-tw** [comment]
Fixed in snap revision >=72.
